module.exports = [
  { label: 'Auckland', value: 'Auckland', n: 523500 },
  { label: 'BOP', value: 'BOP', n: 231900 },
  { label: 'Canterbury', value: 'Canterbury', n: 551400 },
  { label: 'Capital and Coast', value: 'Capital and Coast', n: 312700 },
  { label: 'Counties Manukau', value: 'Counties Manukau', n: 546600 },
  { label: 'Hawkes Bay', value: 'Hawkes Bay', n: 163900 },
  { label: 'Hutt Valley', value: 'Hutt Valley', n: 147900 },
  { label: 'Lakes', value: 'Lakes', n: 108500 },
  { label: 'MidCentral', value: 'MidCentral', n: 176600 },
  { label: 'Nelson Marlborough', value: 'Nelson Marlborough', n: 148800 },
  { label: 'Northland', value: 'Northland', n: 175400 },
  { label: 'South Canterbury', value: 'South Canterbury', n: 59600 },
  { label: 'Southern', value: 'Southern', n: 324300 },
  { label: 'Tairawhiti', value: 'Tairawhiti', n: 48500 },
  { label: 'Taranaki', value: 'Taranaki', n: 118100 },
  { label: 'Waikato', value: 'Waikato', n: 408800 },
  { label: 'Wairarapa', value: 'Wairarapa', n: 44500 },
  { label: 'Waitemata', value: 'Waitemata', n: 606000 },
  { label: 'West Coast', value: 'West Coast', n: 32500 },
  { label: 'Whanganui', value: 'Whanganui', n: 64100 }
]
