graph TD
Popln(Population<br>N=XXXXX) -->|80% Adult| Adults[Adults<br>N=XXXX]
Adults -->|Stroke Incidence<br>147/100,000| Strokes[Strokes]

Strokes -->|Ischemic 81%|Ischemic[Ischemic<br>N=XXXXX]
Strokes -->|Hemorrhagic 19%| ICH[Hemorrhage<br>N=XXXX]

Ischemic -->|LVO 40%|LVO[LVO<br>N=XXXX]
Ischemic -->|SVO 60%|SVO[SVO<br>N=XXXX]

LVO-->|NIHSS>=6 80%|Moderate[NIHSS>=6<br>N=XXXX]
LVO-->|NIHSS< 6 20%|Mild[NIHSS<6<br>N=XXXX]

Moderate-->|Onset/LSW <12h<br>78%|KTO[KTO<br>N=XXXX]
Moderate-->|Unknown Onset<br>15%|SUTO[SUTO<br>N=XXXX]
Moderate-->|Known Onset > 12h<br>7%|GT12h[Late<br>N=XXXX]

KTO-->|<4h<br>XX%|LT4h[0-4h<br>N=XXXX]
KTO-->|>4h<br>XX%|GT4h[4-12h <br>N=XXXX]

GT4h-->Late[Late<br>N=XXXX]

SUTO-->Late

LT4h-->|No Exclusions<br>66%|Inclusion[IVT and PSI Eligible<br>N=XXXX]
LT4h-->|mRS>2, ASPECTS<6<br>34%|Ineligible[Ineligible<br>N=XXXX]

Late-->|No Exclusions<br>25%|Inclusion2[No Exclusions<br>N=XXXX]
Late-->|mRS>2, ASPECTS<6<br>75%|Exclusion[Ineligible<br>N=XXXX]

Inclusion2-->|Favourable CTP 57%|CTPGood[Favourable CTP<br>N=XXXX]
Inclusion2-->|Unfavourable CTP 43%|CTPBad[Unfavourable CTP<br>N=XXXX]

Inclusion-->|Lysis recanalized 5%|Lysed[PSI not required<br>N=XXXX]
Inclusion-->|No recannalization 95%|PSIReqd[PSI required<br>N=XXXX]

CTPGood-->TotalPSI[Total PSI<br>N=XXXX]
PSIReqd-->TotalPSI